### ISSUE TITLE
How setup iron worker for listen events from Amazon S3 ?

### ISSUE THREAD

**Issue by juliocanares** [iron-io/lambda-vs-ironworker#1]
Hi guys , i want listen events from amazon s3 and resize images , and another thing , how i can listen when the task is complete ?
thanks :D

**Comment by treeder** [comment]
Hi @juliocanares , you could setup an SNS alert from s3 and use your IronWorker webhook: http://dev.iron.io/worker/reference/api/#queue_a_task_from_a_webhook to kick off the worker.

**Comment by juliocanares** [comment]
thanks @treeder , but how I can know that the task is completed ?  , long-poll to the api http://dev.iron.io/worker/reference/api/#get_info_about_a_task ?

**Comment by treeder** [comment]
Currently, that would be the only way yes. There is a feature in the works to support webhook callbacks that would allow you to fire up an IronWorker when it completes. Subscribe/vote on that here: https://trello.com/c/xVwn79L4/36-ironworker-status-callbacks-webhooks
